spring.application.name=library
spring.datasource.url=jdbc:oracle:thin:@libraryDB:1521/FREEPDB1
spring.datasource.username=system
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10