# Stage 1: Build
FROM eclipse-temurin:21 AS builder
WORKDIR /app

COPY gradle/wrapper gradle/wrapper
COPY gradlew .
COPY settings.gradle .
COPY build.gradle .

RUN ./gradlew dependencies --no-daemon

COPY . .

RUN ./gradlew build --no-daemon

# Stage 2: Runtime
FROM eclipse-temurin:21
WORKDIR /app

COPY --from=builder /app/build/libs/user-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8100
CMD ["java", "-jar", "app.jar"]
