services:
  webhook-postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhookDB
    ports:
      - "5432:5432"
    volumes:
      - webhook-postgres-data:/var/lib/postgresql/data

  manager:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - webhook-postgres

volumes:
  webhook-postgres-data: